modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "libgui"
version = "${version}"
displayName = "LibGui"
authors = "Falkreon, Juuz, Kenza"
description = '''
Easy grid-based GUIs for Fabric and Forge.
'''
#logoFile = ""

[[dependencies.libgui]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui]]
modId = "architectury"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"