modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "libgui"
version = "${version}"
displayName = "LibGui"
authors = "Falkreon, Juuz, Kenza"
description = '''
Easy grid-based GUIs for Fabric and Forge.
'''
#logoFile = ""

[[dependencies.libgui]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"